apiVersion: apps/v1
kind: Deployment
metadata:
  name: zahralova-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site_web
  template:
    metadata:
      labels:
        app: site_web
    spec:
      containers:
        - name: zahralova-site
          image: rootroot23/zahralova
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: zahra-service
spec:
  type: NodePort
  selector:
    app: site_web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80      
